### ISSUE TITLE
Slow checkout load 

### ISSUE THREAD

**Issue by mdahamshi** [DePayFi/web3-woocommerce-depay-payments#14]
Hey
Im trying to make this https://taptip.shop/checkout/ checkout load faster, I saw that your plugin load massive js file, Is there anyway to reduce it? if I disable wallets will it help ? can you separate it to multiple files ?

**Comment by 0xNe0x1** [comment]
The answer remains the same as before:

No. We can't improve loading speed or separate into multiple files.

Regarding the size of the JavaScript files, DePay Widgets and other libraries involved in cryptocurrency transactions tend to be large due to the inclusion of extensive and sometimes older cryptography libraries, which are necessary but not always optimized.

The DePay Plugin for WooCommerce employs a deferred loading strategy for JavaScript, as described [here](https://www.w3schools.com/tags/att_script_defer.asp). This method doesn't block the webpage while loading, which generally offers a better user experience than loading scripts only upon user interaction. By deferring the loading, the script is likely to be fully loaded by the time a customer decides to complete their purchase, thus reducing wait time at checkout.
